spring:
  application:
    name: DatHostDemoManager

server:
  port: 9090

ftp:
  local:
    directory: TEMP_DIRECTORY
    archive-directory: ARCHIVE_DIRECTORY
    latest-demos-directory: LATEST_DIRECTORY
    max-archive-demos: 100
    max-latest-demos: 50

  servers:
    - host: HOST
      port: 21
      username: USERNAME
      password: PASSWORD
      demos-folder: RELATIVE_DEMO_PATH

settings:
  delete-from-ftp: false # must be enabled in production, otherwise demos might be packaged multiple times
  run-interval: 10 # how often the demos are fetched in minutes
  minutes-after-demo: 360 # 6 hours - the server time is 2 hours off to local time, so the difference is 120 minutes from the start
  allowed-file-ending: ".dem"
  workshop-image-path: WORKSHOP_IMAGE_PATH