spring:
  application:
    name: DatHostDemoManager

server:
  port: 9090

ftp:
  local:
    directory: TEMP_DIRECTORY
    archive-directory: ARCHIVE_DIRECTORY
    latest-demos-directory: LATEST_DIRECTORY
    max-archive-demos: 100
    max-latest-demos: 50

  servers:
    - host: HOST
      port: 21
      username: USERNAME
      password: PASSWORD
      server-id: SERVER_ID
      demos-folder: RELATIVE_DEMO_PATH
      maps-folder: RELATIVE_MAPS_PATH

settings:
  demos:
    fetch-demos: true # enables whether demos are fetched at all
    delete-demos: true # enables whether the fetched demos are deleted from the ftp server or not. Must be enabled in production, otherwise demos might be packaged multiple times
    run-interval-demo-fetching: 10 # how often the demos are fetched in minutes
    minutes-after-demo: 360 # 6 hours - the server time is 2 hours off to local time, so the difference is 120 minutes from the start
    allowed-file-ending: ".dem"
  maps:
    delete-maps: true
    run-interval-map-deletion: 10
    min-megabytes-maps: 10_000
  workshop-image-path: WORKSHOP_IMAGE_PATH
  dathost-credentials:
    username: USERNAME
    password: PASSWORD